using System.Text.Json;
using System.Text.Json.Nodes;
using TradingBot.Api;
using TradingBot.Options;

namespace TradingBot.Services;

public sealed class DiagnosticsDashboardService(TradingBotOptions options)
{
    private long _sequence;
    private DateTime _lastSummaryUtc = DateTime.MinValue;
    public object Build(BotRuntimeState state)
    {
        var h = RuntimeHealthSnapshot.From(state, options);
        var warnings = new List<string>();
        var sources = new List<string>{"runtimeHealth"};
        if (state.OpportunityFamilyRanking is null) warnings.Add("MissingSource:opportunityFamilyRanking"); else sources.Add("opportunityFamilyRanking");
        if (state.FocusUniverse is null) warnings.Add("MissingSource:focusUniverse"); else sources.Add("focusUniverse");
        if (state.EdgeTransition is null) warnings.Add("MissingSource:edgeTransition"); else sources.Add("edgeTransition");
        if (state.EdgeCompression is null) warnings.Add("MissingSource:edgeCompression"); else sources.Add("edgeCompression");
        if (state.SpreadMicrostructure is null) warnings.Add("MissingSource:spreadMicrostructure"); else sources.Add("spreadMicrostructure");
        var strategyPaperSum = h.StrategyCounters.Values.Sum(x => x.PaperOpened);
        var totalPositive = h.StrategyCounters.Values.Sum(x => x.PositiveEdges);
        if (totalPositive == 0 && (h.OpportunityFamilyPositiveFamilies > 0 || h.EdgeTransitionPositiveCandidates > 0 || h.EdgeCompressionAfterSafetyPositive > 0)) warnings.Add("PositiveCountMismatch");
        if (h.PaperDiagnosticsLimitedPaperOpened != strategyPaperSum) warnings.Add("PaperOpenedStrategySumMismatch");
        if (h.LiveTradingBlockedCount > 0 && string.Equals(options.RuntimeProfile, RuntimeProfileService.ReducedDiagnosticsFullStack, StringComparison.OrdinalIgnoreCase)) warnings.Add("LiveTradingBlockedInReducedDiagnosticsFullStack");
        if (h.SigningAttempts > 0) warnings.Add("SigningAttemptsGreaterThanZero");
        if (options.SpreadMicrostructure.Enabled && state.SpreadMicrostructure is null) warnings.Add("SpreadMicrostructureEnabledButMissing");
        if (h.SignalRPayloadTrimmedTotal != h.SignalRPayloadTrimmedLogged + h.SignalRPayloadTrimmedSuppressed) warnings.Add("SignalRCountersMismatch");
        var consistent = h.OpportunityFamilyRankingConsistent && h.FocusUniverseConsistent && h.EdgeTransitionConsistent && h.EdgeCompressionConsistent && h.SpreadMicrostructureConsistent && h.SignalRLogNoiseControlConsistent;
        var byStrategy = h.StrategyCounters.ToDictionary(x => x.Key, x => (object)x.Value, StringComparer.OrdinalIgnoreCase);
        var summary = new {
            totalCandidates = h.StrategyCounters.Values.Sum(x => x.Candidates), totalPositive, totalValidPricedCandidates = h.StrategyCounters.Values.Sum(x => x.ValidPriced), totalInvalidOrUnpricedCandidates = h.StrategyCounters.Values.Sum(x => x.InvalidOrUnpriced), totalExecutionReady = h.StrategyCounters.Values.Sum(x => x.ExecutionReady), totalShadowWouldOpen = h.StrategyCounters.Values.Sum(x => x.ShadowWouldOpen), totalPaperOpened = strategyPaperSum,
            bestStrategy = BestStrategy(h.StrategyCounters, x => x.BestEdge), bestAfterSafetyEdge = BestEdge(h.StrategyCounters, x => x.BestEdge), bestValidPricedStrategy = BestStrategy(h.StrategyCounters, x => x.BestEdge), bestValidPricedAfterSafetyEdge = BestEdge(h.StrategyCounters, x => x.BestEdge), bestExecutableStrategy = BestStrategy(h.StrategyCounters.Where(x=>x.Value.ExecutionReady>0).ToDictionary(x=>x.Key,x=>x.Value), x => x.BestEdge) ?? "N/A" };
        var top = Math.Max(0, options.DiagnosticsDashboard.IncludeTopItems ? options.DiagnosticsDashboard.TopItemsLimit : 0);
        var dashboard = new {
            generatedAtUtc = DateTime.UtcNow, processRunId = h.ProcessRunId, uptime = h.Uptime.ToString(), snapshotSequence = Interlocked.Increment(ref _sequence), runtimeHealthSequence = h.ScannerCycleId, soakStatusSequence = h.ScannerCycleId, strategySummarySequence = h.ScannerCycleId, generatedFromSources = sources,
            runtimeProfile = new { profile = h.RuntimeProfile, activeStrategies = Split(h.ActiveStrategies), paperEligibleStrategies = Split(h.PaperEligibleStrategies), shadowStrategies = Split(h.ShadowStrategies), diagnosticsOnlyLayers = new[]{"AutoCandidatePricing","OpportunityFamilyRanking","FocusUniverse","EdgeTransition","EdgeCompression","SpreadMicrostructure","SignalRLogNoiseControl","DiagnosticsDashboard"}},
            readiness = new { tradingReadiness = h.TradingReadiness, soakReadiness = h.SoakReadiness, soakReadinessReason = h.SoakReadinessReason, discoveryHealthy = h.DiscoveryHealthy, discoveryMode = h.DiscoverySelectedSource, diagnosticsUniverse = h.DiagnosticsUniverse },
            safety = new { liveTradingBlocked = h.LiveTradingBlockedCount, signingAttempts = h.SigningAttempts, paperOpened = h.PaperDiagnosticsLimitedPaperOpened, paperOpenPositions = h.PaperOpenPositions, paperExposure = h.PaperTotalExposure, paperDiagnosticsLimitedEligible = h.PaperDiagnosticsLimitedEligible, paperDiagnosticsLimitedAllowedStrategy = h.PaperDiagnosticsLimitedAllowedStrategy, paperDiagnosticsLimitedMaxOpenPositions = h.PaperDiagnosticsLimitedMaxOpenPositions, paperDiagnosticsLimitedMaxPaperNotionalPerTrade = h.PaperDiagnosticsLimitedMaxPaperNotionalPerTrade, paperDiagnosticsLimitedMaxPaperTotalExposure = h.PaperDiagnosticsLimitedMaxPaperTotalExposure },
            orderbook = new { stableNow = h.OrderbookStableNow, reducedUniverseStableNow = h.ReducedUniverseOrderbookStableNow, circuitBreakerActive = h.OrderbookCircuitBreakerActive, circuitBreakerState = h.OrderbookCircuitBreakerState, batchBookRequests = h.BatchBookRequests, batchBookBadRequests = h.BatchBookBadRequests, batchBookInvalidTokens = h.BatchBookInvalidTokens, batchBookBadRequestsDeltaWindow = h.BatchBookBadRequestsDeltaWindow, batchBookInvalidTokensDeltaWindow = h.BatchBookInvalidTokensDeltaWindow, postBreakerBadRequestsDeltaWindow = h.PostBreakerBadRequestsDeltaWindow },
            runtimeHealth = new { memoryStable = h.LongRunStable, logVolumeStable = h.RuntimeStatusExportStable, processMb = h.ProcessMemoryMb, deltaMb = 0, slopeMbPerMin = 0, logs = h.RecentLogsCount, executionAudit = h.ExecutionAuditCount, signalR = h.SignalREventBufferCount, quietSuppressed = h.QuietSuppressedTotal },
            strategies = new { active = Split(h.ActiveStrategies), summary, byStrategy },
            singleMarket = new { bestRawEdge = h.SingleMarketBestRawEdge, bestAfterCostEdge = h.SingleMarketBestAfterCostEdge, bestAfterSafetyEdge = h.SingleMarketBestAfterSafetyEdge, positiveBeforeCost = h.SingleMarketPositiveBeforeCost, positiveAfterCost = h.SingleMarketPositiveAfterCost, positiveAfterSafety = h.SingleMarketPositiveAfterSafety, executionReady = h.SingleMarketExecutionReady, validEdgeSamples = h.SingleMarketValidEdgeSamples, afterSafetyEdgeP50 = h.SingleMarketAfterSafetyEdgeP50, afterSafetyEdgeP95 = h.SingleMarketAfterSafetyEdgeP95, afterSafetyEdgeP99 = h.SingleMarketAfterSafetyEdgeP99, afterSafetyEdgeMax = h.SingleMarketAfterSafetyEdgeMax, bestRejectedReason = h.SingleMarketBestRejectedReason },
            opportunityFamilyRanking = new { enabled = h.OpportunityFamilyRankingEnabled, buckets = h.OpportunityFamilyBuckets, bestPricedFamily = h.OpportunityFamilyBestPricedFamily, bestPricedAfterSafetyEdge = h.OpportunityFamilyBestPricedAfterSafetyEdge, positiveFamilies = h.OpportunityFamilyPositiveFamilies, executableFamilies = h.OpportunityFamilyExecutableFamilies, invalidRawSpikeFamilies = h.OpportunityFamilyInvalidRawSpikeFamilies, invalidRawSpikeBestEdge = h.OpportunityFamilyInvalidRawSpikeBestEdge, invalidRawSpikeTopReason = h.OpportunityFamilyInvalidRawSpikeTopReason, consistent = h.OpportunityFamilyRankingConsistent },
            focusUniverse = new { enabled = h.FocusUniverseEnabled, watchlistSize = h.FocusUniverseWatchlistSize, admitted = h.FocusUniverseAdmitted, evicted = h.FocusUniverseEvicted, refreshed = h.FocusUniverseRefreshed, bestStrategy = h.FocusUniverseBestStrategy, bestAfterSafetyEdge = h.FocusUniverseBestAfterSafetyEdge, closestToBreakEvenCount = h.FocusUniverseClosestToBreakEvenCount, executionReady = h.FocusUniverseExecutionReady, paperOpened = h.FocusUniversePaperOpened, consistent = h.FocusUniverseConsistent, topItems = h.FocusUniverseTopItems.Take(top) },
            edgeTransition = new { enabled = h.EdgeTransitionEnabled, tracked = h.EdgeTransitionTracked, improving = h.EdgeTransitionImproving, worsening = h.EdgeTransitionWorsening, stableNearBreakEven = h.EdgeTransitionStableNearBreakEven, alertCandidates = h.EdgeTransitionAlertCandidates, positiveCandidates = h.EdgeTransitionPositiveCandidates, bestStrategy = h.EdgeTransitionBestStrategy, bestCurrentEdge = h.EdgeTransitionBestCurrentEdge, bestDeltaFromFirst = h.EdgeTransitionBestDeltaFromFirst, consistent = h.EdgeTransitionConsistent, topItems = h.EdgeTransitionTopItems.Take(top) },
            edgeCompression = new { enabled = h.EdgeCompressionEnabled, items = h.EdgeCompressionItems, nearBreakEven = h.EdgeCompressionNearBreakEven, compressing = h.EdgeCompressionCompressing, flat = h.EdgeCompressionFlat, rawPositive = h.EdgeCompressionRawPositive, afterCostPositive = h.EdgeCompressionAfterCostPositive, afterSafetyPositive = h.EdgeCompressionAfterSafetyPositive, blockedByMarketSpread = h.EdgeCompressionBlockedByMarketSpread, blockedByCost = h.EdgeCompressionBlockedByCost, blockedBySafety = h.EdgeCompressionBlockedBySafety, bestAfterSafetyEdge = h.EdgeCompressionBestAfterSafetyEdge, bestDistanceToBreakEven = h.EdgeCompressionBestDistanceToBreakEven, medianDistanceToBreakEven = h.EdgeCompressionMedianDistanceToBreakEven, dominantDragComponent = h.EdgeCompressionDominantDragComponent, consistent = h.EdgeCompressionConsistent, topItems = h.EdgeCompressionTopItems.Take(top) },
            spreadMicrostructure = new { enabled = h.SpreadMicrostructureEnabled, items = h.SpreadMicrostructureItems, wideAskSpread = h.SpreadMicrostructureWideAskSpread, thinTopBook = h.SpreadMicrostructureThinTopBook, alreadyNearExecutable = h.SpreadMicrostructureAlreadyNearExecutable, depthSufficient = h.SpreadMicrostructureDepthSufficient, bestAfterSafetyEdge = h.SpreadMicrostructureBestAfterSafetyEdge, bestMoveNeededToBreakEven = h.SpreadMicrostructureBestMoveNeededToBreakEven, medianMoveNeededToBreakEven = h.SpreadMicrostructureMedianMoveNeededToBreakEven, minTicksToBreakEven = h.SpreadMicrostructureMinTicksToBreakEven, medianTicksToBreakEven = h.SpreadMicrostructureMedianTicksToBreakEven, dominantCause = h.SpreadMicrostructureDominantCause, consistent = h.SpreadMicrostructureConsistent, topItems = h.SpreadMicrostructureTopItems.Take(top) },
            signalR = new { payloadTrimmedTotal = h.SignalRPayloadTrimmedTotal, payloadTrimmedLogged = h.SignalRPayloadTrimmedLogged, payloadTrimmedSuppressed = h.SignalRPayloadTrimmedSuppressed, lastEvent = h.SignalRPayloadTrimmedLastEvent, lastItemsBefore = h.SignalRPayloadTrimmedLastItemsBefore, lastItemsAfter = h.SignalRPayloadTrimmedLastItemsAfter, summaryIntervalSeconds = h.SignalRPayloadTrimmedSummaryIntervalSeconds, noiseControlEnabled = h.SignalRLogNoiseControlEnabled, consistent = h.SignalRLogNoiseControlConsistent },
            allowlist = new { healthy = h.AllowlistHealthy, monitoringOnly = h.AllowlistMonitoringOnly, needsPricingPrune = h.AllowlistNeedsPricingPrune, needsRefresh = h.AllowlistNeedsRefresh, reviewOnly = h.AllowlistReviewOnly, classificationTotal = h.AllowlistClassificationTotal, classificationValid = h.AllowlistClassificationValid, refreshAutoApply = options.AllowlistRepair.RefreshPreview.AutoApply },
            diagnostics = new { overallConsistent = consistent, warnings, blockingReasons = warnings.Where(x => x.Contains("GreaterThanZero") || x.Contains("LiveTrading")).ToArray() }
        };
        return dashboard;
    }
    public bool TryWrite(BotRuntimeState state, string root, out object dashboard)
    {
        dashboard = Build(state); if (!options.DiagnosticsDashboard.Enabled || !options.DiagnosticsDashboard.ExportEnabled) return false;
        try { var path = Path.IsPathRooted(options.DiagnosticsDashboard.ExportPath) ? options.DiagnosticsDashboard.ExportPath : Path.Combine(root, options.DiagnosticsDashboard.ExportPath); Directory.CreateDirectory(Path.GetDirectoryName(path)!); var json=JsonSerializer.Serialize(dashboard,new JsonSerializerOptions{WriteIndented=true,PropertyNamingPolicy=JsonNamingPolicy.CamelCase}); var tmp=path+".tmp"; for(var i=0;i<3;i++){try{File.WriteAllText(tmp,json);File.Move(tmp,path,true); return true;}catch(IOException) when(i<2){Thread.Sleep(50);}} return false; } catch(Exception ex){ Console.WriteLine($"[DIAGNOSTICS_DASHBOARD_EXPORT_WARNING] Error={ex.Message}"); return false; }
    }
    public void MaybeLogSummary(object dashboard, bool written)
    {
        if (options.Diagnostics.OperationalQuietMode && DateTime.UtcNow - _lastSummaryUtc < TimeSpan.FromSeconds(Math.Max(1, options.DiagnosticsDashboard.WriteIntervalSeconds))) return;
        _lastSummaryUtc = DateTime.UtcNow;
        var json = JsonSerializer.SerializeToNode(dashboard)!;
        Console.WriteLine($"[DIAGNOSTICS_DASHBOARD_SUMMARY] Enabled={options.DiagnosticsDashboard.Enabled.ToString().ToLowerInvariant()} ExportWritten={written.ToString().ToLowerInvariant()} Path={options.DiagnosticsDashboard.ExportPath} OverallConsistent={json["diagnostics"]?["overallConsistent"]} Warnings={json["diagnostics"]?["warnings"]?.AsArray().Count ?? 0} RuntimeProfile={json["runtimeProfile"]?["profile"]} BestStrategy={json["strategies"]?["summary"]?["bestStrategy"]} BestAfterSafetyEdge={json["strategies"]?["summary"]?["bestAfterSafetyEdge"]} FocusWatchlistSize={json["focusUniverse"]?["watchlistSize"]} EdgeTransitionStableNearBreakEven={json["edgeTransition"]?["stableNearBreakEven"]} SpreadDominantCause={json["spreadMicrostructure"]?["dominantCause"]} SignalRTrimSuppressed={json["signalR"]?["payloadTrimmedSuppressed"]} ProcessRunId={json["processRunId"]}");
    }
    private static string[] Split(string? v)=>string.IsNullOrWhiteSpace(v)?Array.Empty<string>():v.Split('|',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);
    private static string? BestStrategy(IEnumerable<KeyValuePair<string,StrategyRuntimeCounterSnapshot>> s, Func<StrategyRuntimeCounterSnapshot,decimal?> f)=>s.Where(x=>f(x.Value).HasValue).OrderByDescending(x=>f(x.Value)).FirstOrDefault().Key;
    private static decimal? BestEdge(IEnumerable<KeyValuePair<string,StrategyRuntimeCounterSnapshot>> s, Func<StrategyRuntimeCounterSnapshot,decimal?> f)=>s.Select(x=>f(x.Value)).Where(x=>x.HasValue).OrderByDescending(x=>x).FirstOrDefault();
}
