using System.Text.Json;
using TradingBot.Api;
using TradingBot.Models;
using TradingBot.Options;

namespace TradingBot.Services;

public sealed record SpreadMicrostructureItem(int Rank,string Strategy,string MarketIdOrGroupKey,string Title,string MarketShape,decimal RawEdge,decimal AfterCostEdge,decimal AfterSafetyEdge,decimal? CombinedAsk,decimal? CombinedBid,decimal AskMoveNeededToRawBreakEven,decimal AskMoveNeededToAfterSafetyBreakEven,int TicksToRawBreakEven,int TicksToAfterSafetyBreakEven,decimal? YesBestBid,decimal? YesBestAsk,decimal? NoBestBid,decimal? NoBestAsk,decimal? YesSpread,decimal? NoSpread,decimal? TopBookYesAskSize,decimal? TopBookNoAskSize,decimal? MinTopBookAskSize,decimal TopBookDepthNotional,bool DepthSufficientForMinPaperNotional,string LiquidityClass,string MicrostructureCause,string RecommendedAction);
public sealed record SpreadMicrostructureSnapshot(bool Enabled,int Items,int SkippedByOrderbookHealth,int WideAskSpread,int ThinTopBook,int BothWideAndThin,int AlreadyNearExecutable,int DepthSufficient,string BestStrategy,decimal? BestAfterSafetyEdge,decimal? BestMoveNeededToBreakEven,decimal? MedianMoveNeededToBreakEven,decimal? P95MoveNeededToBreakEven,int? MinTicksToBreakEven,decimal? MedianTicksToBreakEven,string DominantCause,bool Consistent,IReadOnlyList<SpreadMicrostructureItem> RankedItems);

public sealed class SpreadMicrostructureService(TradingBotOptions options, OrderBookService orderBooks)
{
    public SpreadMicrostructureSnapshot Update(FocusUniverseSnapshot? focus, EdgeCompressionSnapshot? compression, RuntimeHealthSnapshot health, IReadOnlyDictionary<string,Market> markets, string root)
    {
        var o=options.SpreadMicrostructure; var healthOk=(!o.RequireOrderbookStableNow||health.OrderbookStableNow)&&(!o.RequireReducedUniverseOrderbookStableNow||health.ReducedUniverseOrderbookStableNow);
        var enabled=o.Enabled&&(!o.RequireFocusUniverse||focus?.Enabled==true)&&(!o.RequireEdgeCompression||compression?.Enabled==true); if(!enabled||!healthOk){var s=Snapshot(enabled,Array.Empty<SpreadMicrostructureItem>(),health,enabled&&!healthOk?1:0); if(o.ExportEnabled) Export(s,health,focus,compression,root); return s;}
        var items=new List<SpreadMicrostructureItem>(); var minNotional=Math.Max(options.MinNotionalPerTrade, options.PaperDiagnosticsLimited.MaxPaperNotionalPerTrade);
        foreach(var f in (focus?.Items??Array.Empty<FocusUniverseItem>()).Take(Math.Max(0,o.MaxItems))){ if(!f.ValidPriced||!f.CurrentRawEdge.HasValue||!f.CurrentAfterCostEdge.HasValue||IsInvalid(f.LastRejectedReason)||f.CurrentRawEdge.Value>0.5m) continue; if(!markets.TryGetValue(f.MarketIdOrGroupKey,out var m)||m.clobTokenIds.Count<2) continue; var y=orderBooks.GetCachedOrderBookSnapshot(m.clobTokenIds[0],m.id); var n=orderBooks.GetCachedOrderBookSnapshot(m.clobTokenIds[1],m.id); var ya=y?.Asks.FirstOrDefault(); var na=n?.Asks.FirstOrDefault(); if(ya is null||na is null) continue; var yb=y?.Bids.FirstOrDefault(); var nb=n?.Bids.FirstOrDefault(); var combinedAsk=ya.Price+na.Price; if(combinedAsk<=0m||combinedAsk>1.5m) continue; var combinedBid=(yb?.Price??0m)+(nb?.Price??0m); var raw=1m-combinedAsk; var cost=f.CurrentAfterCostEdge.Value; var safety=f.CurrentAfterSafetyEdge; var moveRaw=Math.Max(0m,-raw); var moveSafety=Math.Max(0m,-safety); var tick=InferTick(y,n); var topNotional=combinedAsk*Math.Min(ya.Size,na.Size); var depthOk=topNotional>=minNotional; var ys=yb is null?(decimal?)null:ya.Price-yb.Price; var ns=nb is null?(decimal?)null:na.Price-nb.Price; var maxSpread=Math.Max(ys??0m,ns??0m); var wide=maxSpread>=Math.Max(tick*2,moveSafety/2m); var thin=!depthOk; var cause=Cause(raw,cost,safety,moveSafety,wide,thin,depthOk,o.NearMoveThreshold); var action=Action(cause,moveSafety,tick); items.Add(new SpreadMicrostructureItem(0,f.Strategy,f.MarketIdOrGroupKey,f.Title,"Binary",raw,cost,safety,combinedAsk,combinedBid,moveRaw,moveSafety,Ceil(moveRaw,tick),Ceil(moveSafety,tick),yb?.Price,ya.Price,nb?.Price,na.Price,ys,ns,ya.Size,na.Size,Math.Min(ya.Size,na.Size),topNotional,depthOk,Liquidity(topNotional,minNotional),cause,action)); }
        var ranked=items.OrderBy(x=>x.AskMoveNeededToAfterSafetyBreakEven).ThenByDescending(x=>x.AfterSafetyEdge).Select((x,i)=>x with{Rank=i+1}).ToArray(); var snap=Snapshot(true,ranked,health,0); if(!options.Diagnostics.OperationalQuietMode) Console.WriteLine($"[SPREAD_MICROSTRUCTURE_SUMMARY] Enabled={snap.Enabled.ToString().ToLowerInvariant()} Items={snap.Items} SkippedByOrderbookHealth={snap.SkippedByOrderbookHealth} WideAskSpread={snap.WideAskSpread} ThinTopBook={snap.ThinTopBook} BothWideAndThin={snap.BothWideAndThin} AlreadyNearExecutable={snap.AlreadyNearExecutable} DepthSufficient={snap.DepthSufficient} BestStrategy={snap.BestStrategy} BestAfterSafetyEdge={Fmt(snap.BestAfterSafetyEdge)} BestMoveNeededToBreakEven={Fmt(snap.BestMoveNeededToBreakEven)} MedianMoveNeededToBreakEven={Fmt(snap.MedianMoveNeededToBreakEven)} P95MoveNeededToBreakEven={Fmt(snap.P95MoveNeededToBreakEven)} MinTicksToBreakEven={snap.MinTicksToBreakEven?.ToString()??"N/A"} MedianTicksToBreakEven={Fmt(snap.MedianTicksToBreakEven)} DominantCause={snap.DominantCause} Consistent={snap.Consistent.ToString().ToLowerInvariant()}"); if(o.ExportEnabled) Export(snap,health,focus,compression,root); return snap;
    }
    private SpreadMicrostructureSnapshot Snapshot(bool en,IReadOnlyList<SpreadMicrostructureItem>a,RuntimeHealthSnapshot h,int skip){var best=a.FirstOrDefault(); var moves=a.Select(x=>x.AskMoveNeededToAfterSafetyBreakEven).OrderBy(x=>x).ToArray(); var ticks=a.Select(x=>(decimal)x.TicksToAfterSafetyBreakEven).OrderBy(x=>x).ToArray(); var dom=a.GroupBy(x=>x.MicrostructureCause).OrderByDescending(x=>x.Count()).ThenBy(x=>x.Key).FirstOrDefault()?.Key??"Unknown"; var consistent=!(best?.AfterSafetyEdge>0m && h.StrategyCounters.Values.Sum(x=>x.PositiveEdges)==0); return new(en,a.Count,skip,a.Count(x=>x.MicrostructureCause=="WideAskSpread"),a.Count(x=>x.MicrostructureCause=="ThinTopBook"),a.Count(x=>x.MicrostructureCause=="BothWideAndThin"),a.Count(x=>x.MicrostructureCause=="AlreadyNearExecutable"),a.Count(x=>x.DepthSufficientForMinPaperNotional),best?.Strategy??"N/A",best?.AfterSafetyEdge,best?.AskMoveNeededToAfterSafetyBreakEven,P(moves,.5),P(moves,.95),a.Count>0?a.Min(x=>x.TicksToAfterSafetyBreakEven):null,P(ticks,.5),dom,consistent,a);}
    private static string Cause(decimal raw,decimal cost,decimal safety,decimal move,bool wide,bool thin,bool depth,decimal near)=> raw>0&&cost<=0?"CostDragOnly":cost>0&&safety<=0?"SafetyDragOnly":Math.Abs(safety)<=near&&depth?"AlreadyNearExecutable":wide&&thin?"BothWideAndThin":wide?"WideAskSpread":thin?"ThinTopBook":"Unknown";
    private static string Action(string c,decimal move,decimal tick)=> c switch{"AlreadyNearExecutable"=>"NearExecutableButNoPositiveEdge","ThinTopBook"=>"IgnoreThinBook","BothWideAndThin"=>"IgnoreThinBook","WideAskSpread"=>"WatchForAskCompression","Unknown"=>move<=tick?"KeepWatching":"NoAction",_=>"NoAction"};
    private static string Liquidity(decimal n,decimal min)=> n<=0?"Unknown":n<min?"Thin":n<min*5?"Moderate":"Deep"; private static int Ceil(decimal v,decimal t)=> (int)Math.Ceiling(v/Math.Max(0.001m,t)); private static decimal InferTick(CachedOrderBookSnapshot? a,CachedOrderBookSnapshot? b)=>0.001m; private static decimal? P(decimal[]v,double p)=>v.Length==0?null:v[(int)Math.Clamp(Math.Ceiling(p*v.Length)-1,0,v.Length-1)]; private static bool IsInvalid(string? r){var s=r??""; return new[]{"MissingYesAsk","MissingNoAsk","SuspiciousYesNoAskSum","TokenOutcomeMappingUnverified","ReviewOnly","DataQualityRejected","MissingPricing"}.Any(x=>s.Contains(x,StringComparison.OrdinalIgnoreCase));} private static string Fmt(decimal? v)=>v?.ToString("0.####")??"N/A";
    private void Export(SpreadMicrostructureSnapshot s,RuntimeHealthSnapshot h,FocusUniverseSnapshot? f,EdgeCompressionSnapshot? e,string root){try{var path=Path.Combine(root,"exports/spread-microstructure-latest.json");Directory.CreateDirectory(Path.GetDirectoryName(path)!);var payload=new{generatedAtUtc=DateTime.UtcNow,h.ProcessRunId,h.Uptime,enabled=s.Enabled,diagnosticsOnly=options.SpreadMicrostructure.DiagnosticsOnly,focusUniverseEnabled=f?.Enabled??false,edgeCompressionEnabled=e?.Enabled??false,h.PaperDiagnosticsLimitedEligible,h.OrderbookStableNow,h.ReducedUniverseOrderbookStableNow,items=s.Items,skippedByOrderbookHealth=s.SkippedByOrderbookHealth,wideAskSpread=s.WideAskSpread,thinTopBook=s.ThinTopBook,bothWideAndThin=s.BothWideAndThin,alreadyNearExecutable=s.AlreadyNearExecutable,depthSufficient=s.DepthSufficient,bestAfterSafetyEdge=s.BestAfterSafetyEdge,bestMoveNeededToBreakEven=s.BestMoveNeededToBreakEven,medianMoveNeededToBreakEven=s.MedianMoveNeededToBreakEven,p95MoveNeededToBreakEven=s.P95MoveNeededToBreakEven,minTicksToBreakEven=s.MinTicksToBreakEven,medianTicksToBreakEven=s.MedianTicksToBreakEven,dominantCause=s.DominantCause,consistent=s.Consistent,rankedItems=s.RankedItems}; var json=JsonSerializer.Serialize(payload,new JsonSerializerOptions{WriteIndented=true,PropertyNamingPolicy=JsonNamingPolicy.CamelCase}); var tmp=path+".tmp"; for(var i=0;i<3;i++){try{File.WriteAllText(tmp,json);File.Move(tmp,path,true);break;}catch(IOException) when(i<2){Thread.Sleep(50);}}}catch(Exception ex){Console.WriteLine($"[SPREAD_MICROSTRUCTURE_EXPORT_WARNING] Error={ex.Message}");}}
}
