namespace TradingBot.Api;

public record BotStatusDto(string Mode,bool ScannerActive,string ConnectionStatus,decimal Cash,decimal LockedCapital,decimal Equity,decimal RealizedPnl,decimal ExpectedProfit,int OpenPositions,int SignalCount,DateTime LastScanTime,DateTime LastHeartbeat);
public record OpportunityDto(string Id,DateTime Timestamp,int Rank,string Strategy,string Group,string Market,string Side,decimal EdgePerShare,decimal ExpectedProfit,decimal CostOrProceeds,decimal GuaranteedPayout,decimal QtyAvailable,bool Executable,string Status,string? Reason,long Sequence);
public record TradeLogEntryDto(string Id,DateTime Timestamp,string Strategy,string Side,string Market,decimal Amount,decimal Price,decimal Edge,decimal ExpectedProfit,string Status,string? Reason,long Sequence);
public record PaperPositionDto(string Id,DateTime OpenedAt,DateTime? ClosedAt,string Strategy,string Group,IReadOnlyList<string> Legs,decimal Qty,decimal Cost,decimal CostPerBasket,decimal GuaranteedPayout,decimal MaxPayout,decimal GrossEdgeAtOpen,decimal NetEdgeAtOpen,decimal ExpectedProfit,decimal LockedCapital,string ActiveProfile,string Source,decimal? RealizedPayout,decimal? RealizedProfit,string Status,long Sequence);
public record RiskStateDto(decimal MaxNotionalPerTrade,decimal MinNotionalPerTrade,decimal MinEdgePerShare,decimal MinExpectedProfit,decimal MaxLockedCapital,decimal LockedCapital,int MaxOpenPositions,int OpenPositions,decimal MaxExposurePerGroup,Dictionary<string,decimal> CurrentExposureByGroup,bool AllowBasketArbs,bool AllowSingleMarketArbs,bool AllowCompleteSetSellArbs,bool AllowThresholdArbs,DateTime Timestamp,long Sequence);
public record ScannerStatsDto(
    int MarketsScanned,
    int OrderbooksScanned,
    int OpportunitiesDetected,
    int ExecutableOpportunities,
    int SkippedByRisk,
    int NegativeEdgeSkipped,
    int ZeroEdgeSkipped,
    int PositiveEdgeFound,
    int ExecutableFound,
    int SkippedPositiveEdgeCount,
    int HiddenFromUiCount,
    long ScanDurationMs,
    DateTime LastScanStartedAt,
    DateTime LastScanCompletedAt,
    string? LastError,
    int TotalMarketsDiscovered,
    int ActiveMarketsDiscovered,
    int DiscoveryPagesFetched,
    int CurrentRollingScanOffset,
    int RollingScanBatchSize,
    int MarketsScannedThisCycle,
    int EstimatedCyclesToFullCoverage,
    DateTime LastFullDiscoveryStartedAt,
    DateTime LastFullDiscoveryCompletedAt,
    long LastFullDiscoveryDurationMs,
    long LastScanDurationMs,
    int OrderbooksRequested,
    int OrderbooksSucceeded,
    int OrderbooksFailed,
    int PositiveEdgeFoundCycle,
    int ExecutableFoundCycle,
    int EmptyCyclesSinceLastOpportunity,
    int ConfiguredMarketScanLimit,
    int ConfiguredMaxMarketsToDiscover,
    int EffectiveMarketLimit,
    int ScanBatchSizeConfigured,
    DateTime? LastEmptyExecutableCycleAt,
    int SkippedBelowMinEdge,
    int SkippedBelowMinProfit,
    int SkippedInsufficientLiquidity,
    int SkippedMissingBothSides,
    int SkippedStaleOrderbook,
    int SkippedRiskLimit,
    int SkippedOther,
    bool DiscoveryHealthy = true,
    int RawMarketsLoaded = 0,
    int UniqueMarketsLoaded = 0,
    int InactiveSkipped = 0,
    int SkippedClosed = 0,
    int SkippedArchived = 0,
    int SkippedMissingTokenIds = 0,
    int SkippedInvalidShape = 0,
    string PaginationMode = "offset",
    string? LastPaginationCursor = null,
    string? LastDiscoveryWarning = null,
    DateTime LastDiscoveryCompletedAt = default,
    TradingBot.Models.OpportunityDiagnosticsSnapshot? Diagnostics = null,
    long Sequence = 0)
{
    // Backward-compatible constructor for call sites that predate discovery diagnostics fields.
    public ScannerStatsDto(
        int MarketsScanned,
        int OrderbooksScanned,
        int OpportunitiesDetected,
        int ExecutableOpportunities,
        int SkippedByRisk,
        int NegativeEdgeSkipped,
        int ZeroEdgeSkipped,
        int PositiveEdgeFound,
        int ExecutableFound,
        int SkippedPositiveEdgeCount,
        int HiddenFromUiCount,
        long ScanDurationMs,
        DateTime LastScanStartedAt,
        DateTime LastScanCompletedAt,
        string? LastError,
        int TotalMarketsDiscovered,
        int ActiveMarketsDiscovered,
        int DiscoveryPagesFetched,
        int CurrentRollingScanOffset,
        int RollingScanBatchSize,
        int MarketsScannedThisCycle,
        int EstimatedCyclesToFullCoverage,
        DateTime LastFullDiscoveryStartedAt,
        DateTime LastFullDiscoveryCompletedAt,
        long LastFullDiscoveryDurationMs,
        long LastScanDurationMs,
        int OrderbooksRequested,
        int OrderbooksSucceeded,
        int OrderbooksFailed,
        int PositiveEdgeFoundCycle,
        int ExecutableFoundCycle,
        int EmptyCyclesSinceLastOpportunity,
        int ConfiguredMarketScanLimit,
        int ConfiguredMaxMarketsToDiscover,
        int EffectiveMarketLimit,
        int ScanBatchSizeConfigured,
        DateTime? LastEmptyExecutableCycleAt,
        int SkippedBelowMinEdge,
        int SkippedBelowMinProfit,
        int SkippedInsufficientLiquidity,
        int SkippedMissingBothSides,
        int SkippedStaleOrderbook,
        int SkippedRiskLimit,
        int SkippedOther,
        TradingBot.Models.OpportunityDiagnosticsSnapshot? Diagnostics,
        long Sequence)
        : this(
            MarketsScanned,
            OrderbooksScanned,
            OpportunitiesDetected,
            ExecutableOpportunities,
            SkippedByRisk,
            NegativeEdgeSkipped,
            ZeroEdgeSkipped,
            PositiveEdgeFound,
            ExecutableFound,
            SkippedPositiveEdgeCount,
            HiddenFromUiCount,
            ScanDurationMs,
            LastScanStartedAt,
            LastScanCompletedAt,
            LastError,
            TotalMarketsDiscovered,
            ActiveMarketsDiscovered,
            DiscoveryPagesFetched,
            CurrentRollingScanOffset,
            RollingScanBatchSize,
            MarketsScannedThisCycle,
            EstimatedCyclesToFullCoverage,
            LastFullDiscoveryStartedAt,
            LastFullDiscoveryCompletedAt,
            LastFullDiscoveryDurationMs,
            LastScanDurationMs,
            OrderbooksRequested,
            OrderbooksSucceeded,
            OrderbooksFailed,
            PositiveEdgeFoundCycle,
            ExecutableFoundCycle,
            EmptyCyclesSinceLastOpportunity,
            ConfiguredMarketScanLimit,
            ConfiguredMaxMarketsToDiscover,
            EffectiveMarketLimit,
            ScanBatchSizeConfigured,
            LastEmptyExecutableCycleAt,
            SkippedBelowMinEdge,
            SkippedBelowMinProfit,
            SkippedInsufficientLiquidity,
            SkippedMissingBothSides,
            SkippedStaleOrderbook,
            SkippedRiskLimit,
            SkippedOther,
            DiscoveryHealthy: true,
            RawMarketsLoaded: 0,
            UniqueMarketsLoaded: 0,
            InactiveSkipped: 0,
            SkippedClosed: 0,
            SkippedArchived: 0,
            SkippedMissingTokenIds: 0,
            SkippedInvalidShape: 0,
            PaginationMode: "offset",
            LastPaginationCursor: null,
            LastDiscoveryWarning: null,
            LastDiscoveryCompletedAt: LastFullDiscoveryCompletedAt,
            Diagnostics,
            Sequence)
    {
    }
}

public record TerminalLogEntryDto(string Id,DateTime Timestamp,string Level,string Source,string Message,long Sequence);
public record EquityPointDto(DateTime Timestamp, decimal Equity, long Sequence);
public record BotControlStateDto(bool IsPaused, string Reason, DateTime UpdatedAtUtc, long Sequence);

public record VerifiedGroupDiagnosticDto(string GroupKey,int RequiredMarketCount,int ResolvedMarketCount,int MissingMarketCount,string EvaluationStatus,string SkipReason,decimal? BestEdge,int MissingNoAskCount,int InsufficientLiquidityCount,IReadOnlyList<string> MissingMarketSamples,IReadOnlyList<string> MissingConditionSamples);
public record VerifiedGroupPricingDto(string GroupKey,int Legs,decimal GuaranteedPayout,decimal NoAskSum,decimal MinNoAsk,decimal MaxNoAsk,decimal AverageNoAsk,decimal GrossEdge,decimal Fees,decimal Slippage,decimal SafetyBuffer,decimal NetEdge,decimal ExecutableQty,decimal ExpectedProfit,string SkipReason,IReadOnlyList<string> FormulaWarnings);
public record VerifiedBasketSensitivityDto(decimal Actual,decimal ZeroFees,decimal ZeroSlippage,decimal ZeroFeesZeroSlippage,decimal RawOnly,decimal HalfFeesHalfSlippage);
public record VerifiedBasketBreakEvenDto(decimal MaxTotalCostsToBreakEven,decimal CurrentTotalCosts,decimal CostReductionNeeded,decimal MaxFeePerLegAtCurrentSlippage,decimal MaxSlippagePerLegAtCurrentFees);
public record VerifiedBasketCostBreakdownDto(string GroupKey,int Legs,decimal GuaranteedPayout,decimal NoAskSum,decimal GrossEdge,decimal Fees,decimal Slippage,decimal Safety,decimal NetEdge,decimal CurrentTotalCosts,decimal CostReductionNeeded,string Classification,string DominantCostComponent,VerifiedBasketSensitivityDto SensitivityScenarios,VerifiedBasketBreakEvenDto BreakEvenThresholds);
public record VerifiedBasketScreenerDto(string ActiveProfile,string ExperimentalProfile,DateTime Timestamp,IReadOnlyList<object> VerifiedGroups,IReadOnlyList<object> Ranking,IReadOnlyList<object> NearExecutableBaskets,IReadOnlyList<object> ExperimentalCandidates,IReadOnlyList<object> StableExperimentalCandidates,IReadOnlyList<object> ActiveProfileExecutable,IReadOnlyList<object> DiagnosticsOnlyPositive,IReadOnlyList<string> Profiles,object? BestByActiveProfile,object? BestByRawEdge,object? BestByConservative,object? BestByPolymarketApprox,object? BestByRaw,object? BestNearExecutable,IReadOnlyList<object> UnresolvedConfiguredGroups);
public record MultiOutcomeDiagnosticsDto(int CandidateGroupsCount,int VerifiedGroupsCount,int RejectedGroupsCount,int ExecutableGroupsCount,Dictionary<string,int> RejectedByReason,IReadOnlyList<string> TopRejectedSamples,IReadOnlyList<string> TopCandidateGroupsForVerification,int AllowlistLoadedCount,IReadOnlyList<string> MissingVerifiedGroups,string LastScanId,DateTime Timestamp,long Sequence,int VerifiedConfiguredCount=0,int VerifiedResolvedCount=0,int VerifiedMismatchCount=0,int VerifiedEvaluatedCount=0,int VerifiedExecutableCount=0,IReadOnlyList<VerifiedGroupDiagnosticDto>? VerifiedGroups=null,string? TopVerifiedGroupSkipReason=null,IReadOnlyList<VerifiedGroupPricingDto>? VerifiedGroupPricing=null,IReadOnlyList<VerifiedBasketCostBreakdownDto>? VerifiedBasketCostBreakdown=null);
