export type BotMode = 'DRY_RUN' | 'PAPER' | 'LIVE' | 'UNKNOWN';
export type ConnectionStatus = 'CONNECTED' | 'RECONNECTING' | 'DISCONNECTED' | 'MOCK';

export interface BotStatus { mode: BotMode; scannerActive: boolean; connectionStatus: ConnectionStatus; cash: number; lockedCapital: number; equity: number; realizedPnl: number; expectedProfit: number; openPositions: number; signalCount: number; lastScanTime: string; lastHeartbeat: string; }
export interface Opportunity { id: string; timestamp: string; rank: number; strategy: string; group: string; market: string; side: string; edgePerShare: number; expectedProfit: number; costOrProceeds: number; guaranteedPayout: number; qtyAvailable: number; executable: boolean; status: 'DETECTED'|'EXECUTABLE'|'DRY_RUN'|'PAPER_EXECUTED'|'SKIPPED'|'EXPIRED'; reason?: string; sequence?: number; }
export interface TradeLogEntry { id: string; timestamp: string; strategy: string; side: string; market: string; amount: number; price: number; edge: number; expectedProfit: number; status: 'DRY_RUN'|'PAPER_EXECUTED'|'SKIPPED'|'FAILED'; reason?: string; sequence?: number; }
export interface PaperPosition { id: string; openedAt: string; closedAt?: string; strategy: string; group: string; legs: string[]; cost: number; guaranteedPayout: number; expectedProfit: number; realizedPayout?: number; realizedProfit?: number; status: 'OPEN'|'CLOSED'|'SIMULATED_CLOSED'; sequence?: number; }
export interface ScannerStats { marketsScanned: number; orderbooksScanned: number; opportunitiesDetected: number; executableOpportunities: number; skippedByRisk: number; scanDurationMs: number; lastScanStartedAt: string; lastScanCompletedAt: string; }
export interface RiskState { maxNotionalPerTrade: number; minNotionalPerTrade: number; minEdgePerShare: number; minExpectedProfit: number; maxLockedCapital: number; lockedCapital: number; maxOpenPositions: number; openPositions: number; maxExposurePerGroup: number; currentExposureByGroup: Record<string, number>; allowBasketArbs: boolean; allowSingleMarketArbs: boolean; allowCompleteSetSellArbs: boolean; allowThresholdArbs: boolean; }
export interface TerminalLogEntry { id: string; timestamp: string; level: 'info'|'warn'|'error'|'success'; source: string; message: string; sequence?: number; }
