namespace TradingBot.Models;

public record OrderBookServiceStats(
    long BatchRequests,
    long BatchBooksLoaded,
    long SingleRequests,
    long CacheHits,
    long SnapshotCacheHits,
    long Timeouts,
    long HttpErrors,
    long ParseErrors,
    long BookCacheMisses,
    long BatchBadRequests = 0,
    long BatchTimeouts = 0,
    long BatchRetrySuccesses = 0,
    long BatchInvalidTokens = 0,
    long BatchSuppressedErrors = 0,
    int QuarantinedTokens = 0,
    int BatchBookErrorSampleCount = 0,
    long BatchBookSplitRetriesAttempted = 0,
    long BatchBookSplitRetrySucceeded = 0,
    long BatchBookSplitRetryFailed = 0,
    long BatchBookSingleTokenFailures = 0,
    long BatchBookSingleTokenQuarantined = 0,
    long BatchBookSkippedQuarantinedTokens = 0,
    long BatchBookSkippedMarketsWithQuarantinedTokens = 0,
    long BatchBookRepeatedInvalidTokenAfterQuarantine = 0,
    int OrderbookUnavailableMarkets = 0,
    int InvalidTokenQuarantineActive = 0,
    long InvalidTokenQuarantineAdded = 0,
    long InvalidTokenQuarantineExpired = 0,
    long BatchBookRequestsAvoidedByQuarantine = 0,
    long MarketsSkippedByInvalidTokenQuarantine = 0,
    int MarketOrderbookQuarantineActive = 0,
    long MarketOrderbookQuarantineAdded = 0,
    long MarketOrderbookQuarantineExpired = 0,
    long MarketsSkippedByMarketOrderbookQuarantine = 0,
    long BatchBookRequestsAvoidedByMarketQuarantine = 0,
    bool OrderbookCircuitBreakerActive = false,
    string OrderbookCircuitBreakerState = "Closed",
    long OrderbookCircuitBreakerOpenCount = 0,
    long OrderbookCircuitBreakerCooldownRemainingSeconds = 0,
    long OrderbookCircuitBreakerHalfOpenAttempts = 0,
    long OrderbookCircuitBreakerHalfOpenSucceeded = 0,
    long OrderbookCircuitBreakerHalfOpenFailed = 0,
    DateTime? OrderbookCircuitBreakerHalfOpenStartedUtc = null,
    long OrderbookCircuitBreakerHalfOpenAgeSeconds = 0,
    long OrderbookCircuitBreakerHalfOpenMaxSeconds = 0,
    long OrderbookCircuitBreakerHalfOpenTimedOutCount = 0,
    long BatchBookCanaryTimeouts = 0,
    long BatchBookCanaryInvalidTokens = 0,
    long BatchBookCanaryOrderbookUnavailable = 0,
    string OrderbookCircuitBreakerLastHalfOpenFailureReason = "",
    long OrderbookCircuitBreakerCooldownExtensions = 0,
    string OrderbookCircuitBreakerLastOpenReason = "",
    DateTime? OrderbookCircuitBreakerRecoveringSinceUtc = null,
    long OrderbookCircuitBreakerRecoveryRemainingSeconds = 0,
    long OrderbookCircuitBreakerReopenedAfterClose = 0,
    long OrderbookRequestsBlockedByCircuitBreaker = 0,
    long OrderbookPostCloseBadRequests = 0,
    long OrderbookPostCloseInvalidTokens = 0,
    long SingleTokenIsolationBudgetExhausted = 0,
    long BatchBookBadRequestsPreventedEstimate = 0,
    long BatchBookCanaryRequests = 0,
    long BatchBookCanaryBadRequests = 0,
    long BatchBookRecoveryRequests = 0,
    long BatchBookRecoveryBadRequests = 0,
    long OrderbookRecoveryLimitedRequests = 0,
    long OrderbookRecoveryLimitedMarkets = 0,
    long OrderbookRecoveryBadRequests = 0,
    long OrderbookRecoveryInvalidTokens = 0,
    long OrderbookRecoverySucceededCount = 0,
    long OrderbookRecoveryFailedCount = 0,
    long BatchBookNormalRequests = 0,
    long BatchBookNormalBadRequests = 0,
    long BatchBookNormalRequestsBeforeBreakerOpen = 0,
    long BatchBookNormalBadRequestsBeforeBreakerOpen = 0,
    long BatchBookNormalRequestsAfterBreakerOpen = 0,
    long BatchBookNormalBadRequestsAfterBreakerOpen = 0,
    long QuarantinedMarketsReintroducedBlocked = 0,
    long QuarantinedTokensReintroducedBlocked = 0,
    bool ReducedUniverseScanPausedByOrderbookHealth = false,
    bool ReducedUniverseOrderbookRecoveryMode = false,
    long ReducedUniverseOrderbookRecoveryCleanWindowSeconds = 0,
    long ReducedUniversePostRecoveryBadRequests = 0,
    bool MarketOrderbookQuarantineLifecycleBalanced = true,
    bool InvalidTokenQuarantineLifecycleBalanced = true,
    string OrderbookQuarantineLifecycleMismatchReason = "",
    long InFlightBeforeBreakerCompletedAfterOpen = 0,
    long InFlightBeforeBreakerBadRequestsAfterOpen = 0,
    long TruePostBreakerNormalRequests = 0,
    long TruePostBreakerBadRequests = 0,
    int ReducedUniverseBadHistoryActive = 0,
    bool ReducedUniverseBadHistoryLoaded = false,
    int ReducedUniverseBadHistoryExpired = 0
);
